name: Feature Request
description: Suggest a new feature or enhancement for TermiVoxed
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - san-gitlogin

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your feedback helps us improve TermiVoxed.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Duplicate Check
      description: Please check if a similar request already exists
      options:
        - label: I have searched the existing issues and this feature has not been requested
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - TTS / Voice Generation
        - Voice Cloning
        - Subtitle Styling
        - Timeline Editor
        - Video Export
        - AI Script Generation
        - User Interface
        - API / Integration
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: I have tried...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - I can help with testing
        - I can help with documentation
        - I can contribute code (with guidance)
        - I can fully implement this feature
        - I cannot contribute but would appreciate this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, screenshots, or examples
