// Project types
export interface VideoInfo {
  id: string
  name: string
  path: string
  order: number
  duration: number | null
  width: number | null
  height: number | null
  fps: number | null
  codec: string | null
  aspect_ratio: number | null
  orientation: string | null
  segments_count: number
  file_exists: boolean  // Whether the video file exists on disk
  // Timeline position fields for repositioning videos on the timeline
  timeline_start: number | null
  timeline_end: number | null
}

export interface Project {
  name: string
  videos: VideoInfo[]
  active_video_id: string | null
  created_at: string
  modified_at: string
  background_music_path: string | null
  export_quality: string
  include_subtitles: boolean
  total_segments: number
}

export interface ProjectListItem {
  name: string
  video_count: number
  created_at: string
  modified_at: string
  segments_count: number
}

// Segment types
export interface Segment {
  id: string
  name: string
  video_id: string | null
  start_time: number
  end_time: number
  duration: number
  text: string
  language: string
  voice_id: string
  rate: string
  volume: string
  pitch: string
  audio_path: string | null
  subtitle_path: string | null
  // Subtitle settings
  subtitle_enabled: boolean
  subtitle_font: string
  subtitle_size: number
  subtitle_color: string
  subtitle_position: number
  subtitle_border_enabled: boolean
  subtitle_border_style: number
  subtitle_outline_width: number
  subtitle_outline_color: string
  subtitle_shadow: number
  subtitle_shadow_color: string
  // Audio analysis
  estimated_audio_duration: number | null
  audio_fits_segment: boolean | null
  // Cross-video extension
  extends_to_next_video: boolean
  overflow_duration: number | null  // How much extends into next video
  next_video_name: string | null    // Name of next video (for UI display)
}

export interface SubtitleStyle {
  enabled: boolean
  font: string
  size: number
  color: string
  position: number
  border_enabled: boolean
  border_style: number
  outline_width: number
  outline_color: string
  shadow: number
  shadow_color: string
}

export interface SegmentCreate {
  name: string
  start_time: number
  end_time: number
  text: string
  language: string
  voice_id?: string
  extends_to_next_video?: boolean
}

// TTS types
export interface Voice {
  name: string
  short_name: string
  gender: string
  language: string
  locale: string
}

// LLM types
export interface LLMProvider {
  type: 'ollama' | 'openai' | 'anthropic' | 'google' | 'custom'
  api_key?: string
  endpoint?: string
  model: string
}

export interface SegmentDescription {
  start_time: number
  end_time: number
  description: string
  keywords?: string[]
}

export interface ScriptStyle {
  tone: string
  style: string
  audience: string
  length: string
  language: string
}

export interface GeneratedScript {
  segment_index: number
  start_time: number
  end_time: number
  text: string
  estimated_duration: number
  word_count: number
  fits_duration: boolean
  confidence: number
}

export interface AutoGeneratedSegment {
  segment_index: number
  name: string
  start_time: number
  end_time: number
  description: string
  script: string
  estimated_duration: number
  word_count: number
  fits_duration: boolean
}

export interface AutoSegmentResponse {
  segments: AutoGeneratedSegment[]
  total_segments: number
  total_duration: number
  coverage_percent: number
  all_fit: boolean
  warnings: string[]
  provider_used: string
  model_used: string
}

export interface OllamaModel {
  name: string
  size: string
  modified_at: string
  digest: string
}

// Export types
export interface ExportConfig {
  quality: 'lossless' | 'high' | 'balanced'
  include_subtitles: boolean
  background_music_path?: string
}

export interface ExportProgress {
  stage: string
  message: string
  progress: number
  current_step?: number
  total_steps?: number
  current_segment?: string
  current_voice?: string
  detail?: string
  // ETA and timing info
  eta_seconds?: number
  eta_formatted?: string
  elapsed_seconds?: number
  processing_speed?: number
}

// Timeline view mode
export type TimelineViewMode = 'combined' | 'single'

// Settings
export interface AppSettings {
  storage_dir: string
  projects_dir: string
  tts_proxy_enabled: boolean
  tts_proxy_url: string | null
  default_quality: string
}

export interface LLMSettings {
  openai_api_key: string | null
  anthropic_api_key: string | null
  google_api_key: string | null
  ollama_endpoint: string
  default_provider: string
  default_model: string
}
